Repository SrRapero720/EmbeddiumPlus, pull requests merged in 2024-01, with the labels that each got.

#11 fix typos
  .github/assets/banner.png
  README.md
Labels: Type: enhancement, Severity: Trivial, PR: BugFix

#13 Update Simplified Chinese localization
  src/main/resources/assets/embeddiumplus/lang/zh_cn.json
Labels: Severity: Trivial, PR: Translation, Status: Queue to Merge

#22 Update ru_ru.json
  src/main/resources/assets/embeddiumplus/lang/ru_ru.json
Labels: Type: enhancement, Severity: Trivial, PR: Translation, Status: Queue to Merge
